language: php

before_install:
  - git submodule update --init
  - composer install

php:
  - "nightly"
  - "7.1"

branches:
  only:
    - sasezaki/master
    - sasezaki/develop

script: php test.php


